### PR TITLE
#45 Images for RGM::Spec

### PR DESCRIPTION
**Pull request by AParovyshnaya**
Look up: #45

### CODE REVIEW

**Review by zelenyhleb — COMMENTED** [review]
Paragraph and Point are ok for me, but I didn't get the idea of index-related icons. Could you describe me in outline, please?

**Comment by AParovyshnaya** [comment]
Pink - color of active link. Green - color of passive link. How we know, index is addition for documents. They are not include each others, like point and paragraph. Pink link in index entry goes to point, for example.

**Comment by zelenyhleb** [comment]
Despite the clear idea, as for me, these two icons are too complicated. Could you reword them somehow to be more reconizable in the model tree? 

Thanks in advance.

**Comment by ruspl-afed** [comment]
@AParovyshnaya please split this PR: images for index and index entry could go to another one.

**Comment by AParovyshnaya** [comment]
you can see images in commits or in branch `images`

**Comment by ruspl-afed** [comment]
> you can see images in commits or in branch `images`

yes, I do. but I need only Point and Paragraph at the moment, could you please remove Index images from this PR?

**Comment by zelenyhleb** [comment]
Thank you, @AParovyshnaya. Please, use other PR for further work.

**Pull request closed without merging**
